package com.cloudslip.pipeline.updated.enums;

public enum ApplicationState {
    PENDING_APP_DETAILS_ADDED, PENDING_APP_VPC_AND_CONFIG_DETAILS_ADDED, PENDING_ADVANCE_CONFIGURATION_ADDED, STARTING_INITIALIZATION, INITIALIZATION_RUNNING, INITIALIZATION_SUCCESS, INITIALIZATION_FAILED, UPDATING_CONFIG, UPDATE_SUCCESS
}
