package com.cloudslip.pipeline.updated.enums;

public enum WebSocketMessageType {
    GENERAL, APP_INITIALIZATION_LOG, STARTING_APP_INITIALIZATION, APP_INITIALIZATION_RUNNING, APP_INITIALIZATION_FAILED, APP_INITIALIZATION_SUCCESS,
    NEW_GIT_COMMIT, STARTING_PIPELINE_FOR_GIT_COMMIT,
    PIPELINE_STEP_LOG, PIPELINE_STEP_PENDING, PIPELINE_STEP_RUNNING, PIPELINE_STEP_SUCCESS, PIPELINE_STEP_FAILED
}
