application:
  name: cloudslip-pipeline
  message: Welcome to cloudslip-pipeline
server:
  port: 9081

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web:
      exposure:
        include: \\*
  metrics:
    export.prometheus.enabled: true
  security:
    enabled: false

jenkins:
  url: http://35.239.103.165:8080/
  user: admin
  token: 11cf0521b23f30aa1bdff1b97b5096b559
  app-build-trigger: AUTOMATIC

github:
  token: 993bbae40025538b9396c8b772b54ac02920ae26
  webhook-url:  http://55aad076.ngrok.io/api/app-commit-state/generate-state
  commitSyncLimit: 20

pipeline-step:
  update-status-url : http://55aad076.ngrok.io/api/app-pipeline-step/update-status

kubernetes:
  url: https://72.22.68.40:443
  port: 443
  auth.token: RwGrYX7122SzpBR7w2hy0LqvET8ZLJN

spring:
  application:
    name: cloudslip-pipeline
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: mongoAdmin
      password: abc123
      database: cloudslip_pipeline

cloudslip:
  kafka:
    force-use: true
    ssl:
      enabled: false
      security-protocol: "SSL"
      protocols: "TLSv1.2"
      truststore-location: "/app/cert/kafka-truststore.jks"
      keystore-location: "/app/cert/kafka-keystore.jks"
      keystore-password: ""
      truststore-password: ""
      key-password: ""
    producer:
      bootstrap-servers: 35.239.103.165:9092
      client-id: ${spring.application.name}
      compression-type: snappy
      acks: 1
      retries: 3
      linger-ms: 1
      batch-size: 16384
      buffer-memory: 30080000
      max-request-size: 30080000
      request-timeout-ms: 60000
    run-cluster-agent-response-fetch-scheduler: true

env:
  facade-service:
    base-url: http://localhost:8080/
    api-access-token: c4167fea0829be75afb94cbaca7e05b590ea44683974f5ec93508bd1b32ed283mwJCSpcnAQ
    connect-to-web-socket: true
  usermanagement-service:
    base-url: http://localhost:8081/